server:
  port: 8083

spring:

  application.name: 'statistics'
  profiles.active: local

  datasource:
    url: jdbc:h2:mem:stub

logging:
  level:
    org.feeder: DEBUG
    org.springframework: WARN
    org.hibernate: WARN
