server:
  port: 8083

spring:

  application.name: 'statistics'
  profiles.active: local

  jpa:
    open-in-view: false

  datasource:
    url: jdbc:h2:mem:stub

security:
  oauth2:
    resource:
      jwt:
        key-value: local_signing_key

feeder:
  security:
    hierarchy.authorityPattern: >
      *:client-admin > *:client-delete > *:client-write > *:client-read
      *:admin > *:delete > *:write > *:read

logging:
  level:
    org.feeder: DEBUG
    org.springframework: WARN
    org.hibernate: WARN
