server:
  port: 8083

spring:

  application.name: 'statistics'
  profiles.active: local

  jpa:
    open-in-view: false

  datasource:
    url: jdbc:h2:mem:stub

  devtools:
    livereload:
      enabled: false

  kafka:
    bootstrapServers: ${bootstrap.servers:localhost:9092}
    consumer:
      group-id: ${spring.application.name}
    producer:
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer

security:
  oauth2:
    resource:
      jwt:
        key-value: local_signing_key

feeder:
  kafka:
    enabled: true
  security:
    hierarchy.authorityPattern: >
      *:client-admin > *:client-delete > *:client-write > *:client-read
      *:admin > *:delete > *:write > *:read

logging:
  level:
    org.feeder: DEBUG
    org.springframework: WARN
    org.hibernate: WARN
    org.apache.kafka: WARN
