name: Non master branch push

on:
  push:
    branches-ignore:
      - 'master'

jobs:

  test:
    name: Test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 1.13

      - name: Maven Package
        run: mvn -B clean package -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Maven Verify
        run: mvn -B clean verify
